from enum import Enum

class ContainerErrorCode(Enum):
    CONTAINER_NOT_CREATED = "CONTAINER_NOT_CREATED"
    PROTECTED_TAG_VIOLATION = "PROTECTED_TAG_VIOLATION"
    TAG_NOT_FOUND = "TAG_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"