name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run release task
        run: ./gradlew release

      - name: Find built JAR
        id: find_jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" | head -n 1)
          echo "jar_file=$JAR_PATH" >> "$GITHUB_OUTPUT"

      - name: Upload release JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: ${{ steps.find_jar.outputs.jar_file }}
