name: Android Gradle CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Show Gradle tasks
        run: ./gradlew tasks

      - name: Build Release JAR with coverage check
        run: ./gradlew release --info

      - name: Check if build directory exists
        run: ls -la build/

      - name: Check libs directory
        run: |
          if [ -d "build/libs" ]; then
            echo "build/libs directory exists"
            ls -l build/libs/
          else
            echo "build/libs directory does not exist"
            echo "Checking for jar files in other locations:"
            find . -name "*.jar"
          fi

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-jar-${{ github.sha }}
          path: build/libs/*.jar
        if: ${{ success() }}