name: Build JAR and Upload

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-jar
          path: build/libs/*.jar
