name: Android Gradle CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_release:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release JAR with coverage check
        run: ./gradlew release

      - name: List built files
        run: ls -l build/libs/

      - name: Upload Release artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-jar-${{ github.sha }}
          path: build/libs/*.jar
